version: '3.3'
services:
    php-apache:
        build: ./php-apache
        ports:
            - 8080:80

        volumes:
            - ./public_html:/var/www/html
        restart: always



     db: 
         image: mariadb:latest
         command: mysqld --innodb-buffer-pool-size=64M
         volumes:
              - ./database:/var/lib/mysql
         restart: always
         environment:
              MYSQL_ROOT_PASSWORD: my_root_pass12345
              MYSQL_DATABASE: database
              MYSQL_USER: user
              MYSQL_PASSWORD: passwd

volumes:
   database:
   public_html:

    