version: '3.3'
services:
    php-apache:
        build: ./php-apache
        ports:
            - 8080:80

        volumes:
            - ./public_html:/var/www/html
        restart: always

volumes:
   public_html:

    